### PR TITLE
Fixes for various HDF5 versions

### PR DESCRIPTION
**Pull request by pmiddend**
I've tested compilation on...

- ...NixOS with 1.14
- ...Debian Bookworm
- ...1.10.5
- ...1.12.0

### CODE REVIEW

**Comment by pmiddend** [comment]
- [x] Tests are still failing
- [x] add GitHub workflows inside this PR.
- [x] Fix ghc-9.2 workflow (something about libffi)
  - Okay, this seems [broken](https://discourse.haskell.org/t/building-a-haskell-project-with-github-workflows-fails-with-libffi-error-only-on-ghc-9-2/10031/2), ignore 9.2 then.

**Comment by pmiddend** [comment]
@picca Can you test again on your system? Then this can be merged finally. :)

**Comment by picca** [comment]
Hello,

Great it compiles now :). thanks a lot

Is it possible to remove theses warning. I like when there is no warning during compilation :).

Is it possible to add debian unstable and debian stable in the CI ?

Cheers

Fred

```
[11 of 60] Compiling Bindings.HDF5.Raw.H5L ( /tmp/hs-hdf5/dist-newstyle/build/x86_64-linux/ghc-9.4.7/hdf5-1.8.11/build/Bindings/HDF5/Raw/H5L.hs, /tmp/hs-hdf5/dist-newstyle/build/x86_64-linux/ghc-9.4.7/hdf5-1.8.11/build/Bindings/HDF5/Raw/H5L.o, /tmp/hs-hdf5/dist-newstyle/build/x86_64-linux/ghc-9.4.7/hdf5-1.8.11/build/Bindings/HDF5/Raw/H5L.dyn_o )

src/Bindings/HDF5/Raw/H5L.hsc:20:1: warning: [-Wunused-imports]
    The import of ‘Bindings.HDF5.Raw.H5O’ is redundant
      except perhaps to import instances from ‘Bindings.HDF5.Raw.H5O’
    To import instances alone, use: import Bindings.HDF5.Raw.H5O()
   |
20 | import Bindings.HDF5.Raw.H5O
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Bindings/HDF5/Raw/H5FD/Direct.hsc:10:1: warning: [-Wunused-imports]
    The import of ‘Bindings.HDF5.Raw.H5’ is redundant
      except perhaps to import instances from ‘Bindings.HDF5.Raw.H5’
    To import instances alone, use: import Bindings.HDF5.Raw.H5()
   |
10 | import Bindings.HDF5.Raw.H5
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Bindings/HDF5/Raw/H5FD/Direct.hsc:11:1: warning: [-Wunused-imports]
    The import of ‘Foreign.Ptr’ is redundant
      except perhaps to import instances from ‘Foreign.Ptr’
    To import instances alone, use: import Foreign.Ptr()
   |
11 | import Foreign.Ptr
   | ^^^^^^^^^^^^^^^^^^

src/Bindings/HDF5/Raw/H5FD/Direct.hsc:12:1: warning: [-Wunused-imports]
    The import of ‘Foreign.Ptr.Conventions’ is redundant
      except perhaps to import instances from ‘Foreign.Ptr.Conventions’
    To import instances alone, use: import Foreign.Ptr.Conventions()
   |
12 | import Foreign.Ptr.Conventions
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Bindings/HDF5/Raw/H5FD/Direct.hsc:13:1: warning: [-Wunused-imports]
    The import of ‘System.IO.Unsafe’ is redundant
      except perhaps to import instances from ‘System.IO.Unsafe’
    To import instances alone, use: import System.IO.Unsafe()
   |
13 | import System.IO.Unsafe(unsafePerformIO)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Bindings/HDF5/Raw/H5FD/Direct.hsc:14:1: warning: [-Wunused-imports]
    The import of ‘Foreign.C.Types’ is redundant
      except perhaps to import instances from ‘Foreign.C.Types’
    To import instances alone, use: import Foreign.C.Types()
   |
14 | import Foreign.C.Types
   | ^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by pmiddend** [comment]
Hi Fred,

yes, the warning annoyed me as well. I'm sure they can be fixed, but the problem is: the imports are necessary for _certain_ combinations of library versions. For others, you get the warnings.

Regarding CI: I would have gone for Debian as CI image from the start, but shockingly, GitHub only provides CI runners for Ubuntu :/ You don't happen to have a Debian GitHub runner lying around? :)

**Comment by picca** [comment]
> Hi Fred,

Hello

> yes, the warning annoyed me as well. I'm sure they can be fixed, but the problem
> is: the imports are necessary for _certain_ combinations of library versions.
> For others, you get the warnings.

Imn that case mayby we shoul dsilent the warning using option directly into the file...

> Regarding CI: I would have gone for Debian as CI image from the start, but
> shockingly, GitHub only provides CI runners for Ubuntu :/ You don't happen to
> have a Debian GitHub runner lying around? :)

Not at all, I am only using the Debian CI on salsa (gitlab of Debian) and the DebCI which use autopkgtest

I tend tu avoid github due to the license issue when you use their infrastructure...

Fred

**Comment by pmiddend** [comment]
Then we will keep with Ubuntu for now.

I will double-check the import warnings and inform you once they're fixed.

**Comment by picca** [comment]
> Then we will keep with Ubuntu for now.

yes

> I will double-check the import warnings and inform you once they're fixed.


thanks

Fred

**Comment by pmiddend** [comment]
Alright, fixed. They even fixed the 9.2 build now.

**Comment by pmiddend** [comment]
Okay @picca, you can test again and then merge in the end.

**Comment by picca** [comment]
I just have these messages on my Debian stable with ghc 9.0.2

Since it is the current stable version in Debian, is it possible to compile it with this version alsao ?

/build/Bindings/HDF5/Dataspace.o, /tmp/hs-hdf5/dist-newstyle/build/x86_64-linux/ghc-9.0.2/hdf5-1.8.11/build/Bindings/HDF5/Dataspace.dyn_o )

src/Bindings/HDF5/Dataspace.hsc:73:1: warning: [-Wdodgy-imports]
    Module ‘Foreign’ does not export ‘And’
   |
73 | import Foreign hiding (And, Xor)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Bindings/HDF5/Dataspace.hsc:73:1: warning: [-Wdodgy-imports]
    Module ‘Foreign’ does not export ‘Xor’
   |
73 | import Foreign hiding (And, Xor)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


I have juste one issue with this. the CI compile against an installed version of ghc and not against the system ghc right ?

nether the system ghc library packages ?

Fred

**Comment by pmiddend** [comment]
I've hopefully fixed the issue with 9.0 now. Please test again.

What do you mean with system/installed version of GHC?

**Comment by picca** [comment]
> I've hopefully fixed the issue with 9.0 now. Please test again.
> 
> What do you mean with system/installed version of GHC?

the gch installed via apt with all the libghc-xxx-dev packages

**Comment by picca** [comment]
----- Le 31 Juil 24, à 15:46, Philipp Middendorf ***@***.*** a écrit :

> I've hopefully fixed the issue with 9.0 now. Please test again.

Debian/unstable ok
Debian/bookworm ok

thanks

**Comment by pmiddend** [comment]
> I've hopefully fixed the issue with 9.0 now. Please test again. What do you mean with system/installed version of GHC?
> the gch installed via apt with all the libghc-xxx-dev packages

Ah, I see what you mean. I think the CI uses ghcup to install the dependencies. I don't have the energy to write a custom CI pipeline that uses `apt-get install`, although it would be nice to have, of course.

**Comment by picca** [comment]
No problem. I can merge ?

**Comment by pmiddend** [comment]
> No problem. I can merge ?
> […](#)
> ----- Le 1 Aoû 24, à 13:24, Philipp Middendorf ***@***.*** a écrit :
> > I've hopefully fixed the issue with 9.0 now. Please test again. What do you mean > with system/installed version of GHC? > the gch installed via apt with all the libghc-xxx-dev packages Ah, I see what you mean. I think the CI uses ghcup to install the dependencies. I don't have the energy to write a custom CI pipeline that uses `apt-get install`, although it would be nice to have, of course. -- Reply to this email directly or view it on GitHub: [#4 (comment)](https://github.com/picca/hs-hdf5/pull/4#issuecomment-2262799530) You are receiving this because you were mentioned. Message ID: ***@***.***>

Yes, I think so.

**Comment by picca** [comment]
Done :)

thanks a lot

Fred

**Comment by pmiddend** [comment]
> Done :) thanks a lot Fred

Can you cut a new release and upload that to hackage?

**Comment by picca** [comment]
Yes I can do this but this evening I need my codes :))

**Comment by picca** [comment]
Hello, I have this candidate

https://hackage.haskell.org/package/hdf5-1.8.12/candidate

Can you check that it seems ok for you. If you want to update the changelog do not hesitate to commit something.

Tell me and I will regenerate the doc and the package.

Cheers

Fred

**Pull request merged**
